version: 1.1.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore mp.pddn\mp.pddn.sln -verbosity quiet
build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
test: off
deploy:
- provider: NuGet
  api_key:
    secure: b4Ec1SXgC2n9ZSaGOdEqDsS3r2mbmmjbzKPpAqybLkk9f/8ZXHNUaE5ImKFw1egj