version: 1.1.{build}
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- ps: nuget restore md.pddn\md.pddn.sln -verbosity quiet -Source http://vvvv.org:8111/guestAuth/app/nuget/v1/FeedService.svc/
build:
  publish_nuget: true
  verbosity: minimal
test: off
before_deploy:
- ps: nuget pack mp.pddn\mp.pddn.csproj -Version $env:appveyor_build_version
deploy:
- provider: NuGet
  api_key:
    secure: b4Ec1SXgC2n9ZSaGOdEqDsS3r2mbmmjbzKPpAqybLkk9f/8ZXHNUaE5ImKFw1egj